# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx/nvdla_zynq_implementation/nvdla_zynq_implementation.srcs/sources_1/bd/nvdla_bd/ip/nvdla_bd_zynq_ultra_ps_e_0_0/nvdla_bd_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'nvdla_bd_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/nvdla_zynq_implementation/nvdla_zynq_implementation.gen/sources_1/bd/nvdla_bd/ip/nvdla_bd_zynq_ultra_ps_e_0_0/nvdla_bd_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'nvdla_bd_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/nvdla_zynq_implementation/nvdla_zynq_implementation.gen/sources_1/bd/nvdla_bd/ip/nvdla_bd_zynq_ultra_ps_e_0_0/nvdla_bd_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'nvdla_bd_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Xilinx/nvdla_zynq_implementation/nvdla_zynq_implementation.srcs/sources_1/bd/nvdla_bd/ip/nvdla_bd_zynq_ultra_ps_e_0_0/nvdla_bd_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'nvdla_bd_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/nvdla_zynq_implementation/nvdla_zynq_implementation.gen/sources_1/bd/nvdla_bd/ip/nvdla_bd_zynq_ultra_ps_e_0_0/nvdla_bd_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'nvdla_bd_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/nvdla_zynq_implementation/nvdla_zynq_implementation.gen/sources_1/bd/nvdla_bd/ip/nvdla_bd_zynq_ultra_ps_e_0_0/nvdla_bd_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'nvdla_bd_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
