# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/nvdla_bd/nvdla_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nvdla_bd || ORIG_REF_NAME==nvdla_bd} -quiet] -quiet

# IP: bd/nvdla_bd/ip/nvdla_bd_zynq_ultra_ps_e_0_0/nvdla_bd_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nvdla_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==nvdla_bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/nvdla_bd/ip/nvdla_bd_NV_nvdla_wrapper_0_0/nvdla_bd_NV_nvdla_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nvdla_bd_NV_nvdla_wrapper_0_0 || ORIG_REF_NAME==nvdla_bd_NV_nvdla_wrapper_0_0} -quiet] -quiet

# IP: bd/nvdla_bd/ip/nvdla_bd_smartconnect_0_0/nvdla_bd_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nvdla_bd_smartconnect_0_0 || ORIG_REF_NAME==nvdla_bd_smartconnect_0_0} -quiet] -quiet

# IP: bd/nvdla_bd/ip/nvdla_bd_smartconnect_1_0/nvdla_bd_smartconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nvdla_bd_smartconnect_1_0 || ORIG_REF_NAME==nvdla_bd_smartconnect_1_0} -quiet] -quiet

# IP: bd/nvdla_bd/ip/nvdla_bd_proc_sys_reset_0_0/nvdla_bd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nvdla_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==nvdla_bd_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/nvdla_bd/ip/nvdla_bd_axi_apb_bridge_0_0/nvdla_bd_axi_apb_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nvdla_bd_axi_apb_bridge_0_0 || ORIG_REF_NAME==nvdla_bd_axi_apb_bridge_0_0} -quiet] -quiet

# IP: bd/nvdla_bd/ip/nvdla_bd_axi_protocol_convert_0_0/nvdla_bd_axi_protocol_convert_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nvdla_bd_axi_protocol_convert_0_0 || ORIG_REF_NAME==nvdla_bd_axi_protocol_convert_0_0} -quiet] -quiet

# XDC: c:/Xilinx/nvdla_zynq_implementation/nvdla_zynq_implementation.gen/sources_1/bd/nvdla_bd/nvdla_bd_ooc.xdc
